CREATE OR REPLACE FILE FORMAT RAW_DATA.FF_CSV
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL')
  EMPTY_FIELD_AS_NULL = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE STAGE RAW_DATA.STG_MEETUP
  FILE_FORMAT = RAW_DATA.FF_CSV;

SHOW STAGES IN SCHEMA RAW_DATA;