CREATE TABLE IF NOT EXISTS RAW_DATA.CATEGORIES (
  category_id VARCHAR, category_name VARCHAR, shortname VARCHAR, sort_name VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW_DATA.CITIES (
  city VARCHAR, city_id VARCHAR, country VARCHAR, distance VARCHAR, latitude VARCHAR,
  localized_country_name VARCHAR, longitude VARCHAR, member_count VARCHAR, ranking VARCHAR,
  state VARCHAR, zip VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW_DATA.EVENTS (
  event_id VARCHAR, created VARCHAR, description VARCHAR, duration VARCHAR, event_url VARCHAR,
  "fee.accepts" VARCHAR, "fee.amount" VARCHAR, "fee.currency" VARCHAR, "fee.description" VARCHAR,
  "fee.label" VARCHAR, "fee.required" VARCHAR, "group.created" VARCHAR, "group.group_lat" VARCHAR,
  "group.group_lon" VARCHAR, group_id VARCHAR, "group.join_mode" VARCHAR, "group.name" VARCHAR,
  "group.urlname" VARCHAR, "group.who" VARCHAR, headcount VARCHAR, how_to_find_us VARCHAR,
  maybe_rsvp_count VARCHAR, event_name VARCHAR, photo_url VARCHAR, "rating.average" VARCHAR,
  "rating.count" VARCHAR, rsvp_limit VARCHAR, event_status VARCHAR, event_time VARCHAR,
  updated VARCHAR, utc_offset VARCHAR, "venue.address_1" VARCHAR, "venue.address_2" VARCHAR,
  "venue.city" VARCHAR, "venue.country" VARCHAR, venue_id VARCHAR, "venue.lat" VARCHAR,
  "venue.localized_country_name" VARCHAR, "venue.lon" VARCHAR, "venue.name" VARCHAR,
  "venue.phone" VARCHAR, "venue.repinned" VARCHAR, "venue.state" VARCHAR, "venue.zip" VARCHAR,
  visibility VARCHAR, waitlist_count VARCHAR, why VARCHAR, yes_rsvp_count VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW_DATA.GROUPS (
  group_id VARCHAR, category_id VARCHAR, "category.name" VARCHAR, "category.shortname" VARCHAR,
  city_id VARCHAR, city VARCHAR, country VARCHAR, created VARCHAR, description VARCHAR,
  "group_photo.base_url" VARCHAR, "group_photo.highres_link" VARCHAR, "group_photo.photo_id" VARCHAR,
  "group_photo.photo_link" VARCHAR, "group_photo.thumb_link" VARCHAR, "group_photo.type" VARCHAR,
  join_mode VARCHAR, lat VARCHAR, link VARCHAR, lon VARCHAR, members VARCHAR, group_name VARCHAR,
  "organizer.member_id" VARCHAR, "organizer.name" VARCHAR, "organizer.photo.base_url" VARCHAR,
  "organizer.photo.highres_link" VARCHAR, "organizer.photo.photo_id" VARCHAR,
  "organizer.photo.photo_link" VARCHAR, "organizer.photo.thumb_link" VARCHAR,
  "organizer.photo.type" VARCHAR, rating VARCHAR, state VARCHAR, timezone VARCHAR, urlname VARCHAR,
  utc_offset VARCHAR, visibility VARCHAR, who VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW_DATA.GROUPS_TOPICS (
  topic_id VARCHAR, topic_key VARCHAR, topic_name VARCHAR, group_id VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW_DATA.MEMBERS (
  member_id VARCHAR, bio VARCHAR, city VARCHAR, country VARCHAR, hometown VARCHAR,
  joined VARCHAR, lat VARCHAR, link VARCHAR, lon VARCHAR, member_name VARCHAR,
  state VARCHAR, member_status VARCHAR, visited VARCHAR, group_id VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW_DATA.MEMBERS_TOPICS (
  topic_id VARCHAR, topic_key VARCHAR, topic_name VARCHAR, member_id VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW_DATA.TOPICS (
  topic_id VARCHAR, description VARCHAR, link VARCHAR, members VARCHAR,
  topic_name VARCHAR, urlkey VARCHAR, main_topic_id VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW_DATA.VENUES (
  venue_id VARCHAR, address_1 VARCHAR, city VARCHAR, country VARCHAR, distance VARCHAR,
  lat VARCHAR, localized_country_name VARCHAR, lon VARCHAR, venue_name VARCHAR,
  rating VARCHAR, rating_count VARCHAR, state VARCHAR, zip VARCHAR, normalised_rating VARCHAR
);

CREATE OR REPLACE TABLE RAW_DATA.CATEGORIES_LOAD
  LIKE RAW_DATA.CATEGORIES COPY GRANTS;
CREATE OR REPLACE TABLE RAW_DATA.CITIES_LOAD
  LIKE RAW_DATA.CITIES COPY GRANTS;
CREATE OR REPLACE TABLE RAW_DATA.EVENTS_LOAD
  LIKE RAW_DATA.EVENTS COPY GRANTS;
CREATE OR REPLACE TABLE RAW_DATA.GROUPS_LOAD
  LIKE RAW_DATA.GROUPS COPY GRANTS;
CREATE OR REPLACE TABLE RAW_DATA.GROUPS_TOPICS_LOAD
  LIKE RAW_DATA.GROUPS_TOPICS COPY GRANTS;
CREATE OR REPLACE TABLE RAW_DATA.MEMBERS_LOAD
  LIKE RAW_DATA.MEMBERS COPY GRANTS;
CREATE OR REPLACE TABLE RAW_DATA.MEMBERS_TOPICS_LOAD
  LIKE RAW_DATA.MEMBERS_TOPICS COPY GRANTS;
CREATE OR REPLACE TABLE RAW_DATA.TOPICS_LOAD
  LIKE RAW_DATA.TOPICS COPY GRANTS;
CREATE OR REPLACE TABLE RAW_DATA.VENUES_LOAD
  LIKE RAW_DATA.VENUES COPY GRANTS;

COPY INTO RAW_DATA.CATEGORIES_LOAD
FROM @RAW_DATA.STG_MEETUP/categories.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_DATA.CITIES_LOAD
FROM @RAW_DATA.STG_MEETUP/cities.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_DATA.EVENTS_LOAD
FROM @RAW_DATA.STG_MEETUP/events.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_DATA.GROUPS_LOAD
FROM @RAW_DATA.STG_MEETUP/groups.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_DATA.GROUPS_TOPICS_LOAD
FROM @RAW_DATA.STG_MEETUP/groups_topics.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV_REPLACE_INVALID)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_DATA.MEMBERS_LOAD
FROM @RAW_DATA.STG_MEETUP/members.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV_REPLACE_INVALID)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_DATA.MEMBERS_TOPICS_LOAD
FROM @RAW_DATA.STG_MEETUP/members_topics.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_DATA.TOPICS_LOAD
FROM @RAW_DATA.STG_MEETUP/topics.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV_REPLACE_INVALID)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_DATA.VENUES_LOAD
FROM @RAW_DATA.STG_MEETUP/venues.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

ALTER TABLE RAW_DATA.CATEGORIES SWAP WITH RAW_DATA.CATEGORIES_LOAD;
ALTER TABLE RAW_DATA.CITIES SWAP WITH RAW_DATA.CITIES_LOAD;
ALTER TABLE RAW_DATA.EVENTS SWAP WITH RAW_DATA.EVENTS_LOAD;
ALTER TABLE RAW_DATA.GROUPS SWAP WITH RAW_DATA.GROUPS_LOAD;
ALTER TABLE RAW_DATA.GROUPS_TOPICS SWAP WITH RAW_DATA.GROUPS_TOPICS_LOAD;
ALTER TABLE RAW_DATA.MEMBERS SWAP WITH RAW_DATA.MEMBERS_LOAD;
ALTER TABLE RAW_DATA.MEMBERS_TOPICS SWAP WITH RAW_DATA.MEMBERS_TOPICS_LOAD;
ALTER TABLE RAW_DATA.TOPICS SWAP WITH RAW_DATA.TOPICS_LOAD;
ALTER TABLE RAW_DATA.VENUES SWAP WITH RAW_DATA.VENUES_LOAD;

DROP TABLE RAW_DATA.CATEGORIES_LOAD;
DROP TABLE RAW_DATA.CITIES_LOAD;
DROP TABLE RAW_DATA.EVENTS_LOAD;
DROP TABLE RAW_DATA.GROUPS_LOAD;
DROP TABLE RAW_DATA.GROUPS_TOPICS_LOAD;
DROP TABLE RAW_DATA.MEMBERS_LOAD;
DROP TABLE RAW_DATA.MEMBERS_TOPICS_LOAD;
DROP TABLE RAW_DATA.TOPICS_LOAD;
DROP TABLE RAW_DATA.VENUES_LOAD;

SELECT 'CATEGORIES' AS table_name, COUNT(*) AS row_count FROM RAW_DATA.CATEGORIES
UNION ALL SELECT 'CITIES', COUNT(*) FROM RAW_DATA.CITIES
UNION ALL SELECT 'EVENTS', COUNT(*) FROM RAW_DATA.EVENTS
UNION ALL SELECT 'GROUPS', COUNT(*) FROM RAW_DATA.GROUPS
UNION ALL SELECT 'GROUPS_TOPICS', COUNT(*) FROM RAW_DATA.GROUPS_TOPICS
UNION ALL SELECT 'MEMBERS', COUNT(*) FROM RAW_DATA.MEMBERS
UNION ALL SELECT 'MEMBERS_TOPICS', COUNT(*) FROM RAW_DATA.MEMBERS_TOPICS
UNION ALL SELECT 'TOPICS', COUNT(*) FROM RAW_DATA.TOPICS
UNION ALL SELECT 'VENUES', COUNT(*) FROM RAW_DATA.VENUES;
