CREATE OR REPLACE TABLE RAW_DATA.MEMBERS (
  member_id VARCHAR, bio VARCHAR, city VARCHAR, country VARCHAR, hometown VARCHAR,
  joined VARCHAR, lat VARCHAR, link VARCHAR, lon VARCHAR, member_name VARCHAR,
  state VARCHAR, member_status VARCHAR, visited VARCHAR, group_id VARCHAR
);

CREATE OR REPLACE TABLE RAW_DATA.MEMBERS_TOPICS (
  topic_id VARCHAR, topic_key VARCHAR, topic_name VARCHAR, member_id VARCHAR
);

CREATE OR REPLACE TABLE RAW_DATA.TOPICS (
  topic_id VARCHAR, description VARCHAR, link VARCHAR, members VARCHAR,
  topic_name VARCHAR, urlkey VARCHAR, main_topic_id VARCHAR
);

CREATE OR REPLACE TABLE RAW_DATA.VENUES (
  venue_id VARCHAR, address_1 VARCHAR, city VARCHAR, country VARCHAR, distance VARCHAR,
  lat VARCHAR, localized_country_name VARCHAR, lon VARCHAR, venue_name VARCHAR,
  rating VARCHAR, rating_count VARCHAR, state VARCHAR, zip VARCHAR, normalised_rating VARCHAR
);

COPY INTO RAW_DATA.TOPICS         FROM @RAW_DATA.STG_MEETUP/topics.csv.gz         FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV) ON_ERROR = 'CONTINUE';
COPY INTO RAW_DATA.VENUES         FROM @RAW_DATA.STG_MEETUP/venues.csv.gz         FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV) ON_ERROR = 'CONTINUE';
COPY INTO RAW_DATA.MEMBERS_TOPICS FROM @RAW_DATA.STG_MEETUP/members_topics.csv.gz FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV) ON_ERROR = 'CONTINUE';
COPY INTO RAW_DATA.MEMBERS        FROM @RAW_DATA.STG_MEETUP/members.csv.gz        FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV) ON_ERROR = 'CONTINUE';

SELECT 'MEMBERS' AS tabla, COUNT(*) AS filas FROM RAW_DATA.MEMBERS
UNION ALL SELECT 'MEMBERS_TOPICS', COUNT(*) FROM RAW_DATA.MEMBERS_TOPICS
UNION ALL SELECT 'TOPICS', COUNT(*) FROM RAW_DATA.TOPICS
UNION ALL SELECT 'VENUES', COUNT(*) FROM RAW_DATA.VENUES;