ALTER FILE FORMAT RAW_DATA.FF_CSV SET REPLACE_INVALID_CHARACTERS = TRUE;

TRUNCATE TABLE RAW_DATA.TOPICS;
COPY INTO RAW_DATA.TOPICS
FROM @RAW_DATA.STG_MEETUP/topics.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

TRUNCATE TABLE RAW_DATA.MEMBERS;
COPY INTO RAW_DATA.MEMBERS
FROM @RAW_DATA.STG_MEETUP/members.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;