-- Optional repair for existing tables loaded before FF_CSV_REPLACE_INVALID existed.
-- Load and validate each replacement before swapping it with the current table.
CREATE OR REPLACE TABLE RAW_DATA.MEMBERS_RELOAD
  LIKE RAW_DATA.MEMBERS COPY GRANTS;

COPY INTO RAW_DATA.MEMBERS_RELOAD
FROM @RAW_DATA.STG_MEETUP/members.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV_REPLACE_INVALID)
ON_ERROR = 'ABORT_STATEMENT';

SELECT 'MEMBERS_RELOAD' AS table_name, COUNT(*) AS row_count
FROM RAW_DATA.MEMBERS_RELOAD;

ALTER TABLE RAW_DATA.MEMBERS SWAP WITH RAW_DATA.MEMBERS_RELOAD;

CREATE OR REPLACE TABLE RAW_DATA.TOPICS_RELOAD
  LIKE RAW_DATA.TOPICS COPY GRANTS;

COPY INTO RAW_DATA.TOPICS_RELOAD
FROM @RAW_DATA.STG_MEETUP/topics.csv.gz
FILE_FORMAT = (FORMAT_NAME = RAW_DATA.FF_CSV_REPLACE_INVALID)
ON_ERROR = 'ABORT_STATEMENT';

SELECT 'TOPICS_RELOAD' AS table_name, COUNT(*) AS row_count
FROM RAW_DATA.TOPICS_RELOAD;

ALTER TABLE RAW_DATA.TOPICS SWAP WITH RAW_DATA.TOPICS_RELOAD;